services:
  ms-clientes:
    build: ./ms-clientes
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - banco-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8081/clientes"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  ms-cuentas:
    build: ./ms-cuentas
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - banco-network
    depends_on:
      ms-clientes:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8082/cuentas"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  banco-network:
    driver: bridge
